#!/usr/bin/env bash
# Validate SSH public keys added or modified between two commits.
#
# Usage: validate-keys.sh <base-ref> <head-ref>
#
# Fails (exit 1) if any added/modified ssh/*.pub file contains something
# that is not a valid, acceptable SSH public key.
#
# Writes "eligible=true|false" to $GITHUB_OUTPUT (when set): true only if
# every changed file in the range is an ssh/*.pub key file, i.e. the PR is
# safe to auto-merge without human review of non-key changes.
set -euo pipefail

base=$1
head=$2
fail=0
eligible=true

# A git failure inside <(...) would be silently ignored; make sure the
# refs are usable before trusting the diffs below.
git merge-base "$base" "$head" > /dev/null

# Triple-dot: diff against the merge base, i.e. only changes the PR introduces
mapfile -t changed < <(git diff --name-only --diff-filter=ACMR "$base...$head" -- )
mapfile -t all_changed < <(git diff --name-only "$base...$head" -- )

# Deletions are allowed (user removal) but any non-key change makes the PR
# ineligible for auto-merge.
for f in "${all_changed[@]}"; do
  case $f in
    ssh/*.pub) ;;
    *)
      echo "note: $f is not an ssh key file; PR will need manual review/merge"
      eligible=false
      ;;
  esac
done

validate_file() {
  local f=$1 lineno=0 keys=0 line info bits type

  if grep -q 'PRIVATE KEY' "$f"; then
    echo "::error file=$f::$f contains private key material -- do not commit private keys!"
    return 1
  fi

  while IFS= read -r line || [ -n "$line" ]; do
    lineno=$((lineno + 1))
    # Skip blank lines and comments
    [[ $line =~ ^[[:space:]]*$ ]] && continue
    [[ $line =~ ^[[:space:]]*# ]] && continue

    if ! info=$(printf '%s\n' "$line" | ssh-keygen -lf - 2>&1); then
      echo "::error file=$f,line=$lineno::not a valid SSH public key: $info"
      return 1
    fi

    bits=$(awk '{print $1}' <<< "$info")
    type=$(awk '{print $NF}' <<< "$info")
    case $type in
      '(DSA)')
        echo "::error file=$f,line=$lineno::DSA keys are obsolete and not accepted"
        return 1
        ;;
      '(RSA)')
        if [ "$bits" -lt 2048 ]; then
          echo "::error file=$f,line=$lineno::RSA keys must be at least 2048 bits (got $bits)"
          return 1
        fi
        ;;
    esac
    keys=$((keys + 1))
    echo "$f:$lineno: OK $info"
  done < "$f"

  if [ "$keys" -eq 0 ]; then
    echo "::error file=$f::$f contains no SSH public keys"
    return 1
  fi
}

for f in "${changed[@]}"; do
  case $f in
    ssh/@*)
      echo "::error file=$f::file names beginning with @ are reserved for autogenerated groups"
      fail=1
      continue
      ;;
    ssh/*.pub)
      ;;
    *)
      # Already flagged as ineligible above; nothing to validate.
      continue
      ;;
  esac

  name=$(basename "$f" .pub)
  if ! [[ $name =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "::error file=$f::key file names may only contain letters, digits, '.', '_' and '-'"
    fail=1
    continue
  fi

  if ! validate_file "$f"; then
    fail=1
  fi
done

if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "eligible=$eligible" >> "$GITHUB_OUTPUT"
fi

if [ "$fail" -ne 0 ]; then
  echo "Key validation FAILED"
  exit 1
fi
echo "Key validation passed (auto-merge eligible: $eligible)"
